version: 2.1
jobs:
  node:
    docker:
      - image: cimg/node:19.2.0

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/app_pisces
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
            
  android-build-and-test:
    working_directory: ~/app_pisces
    docker:
      - image: cimg/android:2022.09
    steps:
      - checkout:
          path: ~/app_pisces
      - attach_workspace:
          at: ~/app_pisces
      - run:
          name: install chruby
          command: |
            wget -O chruby-0.3.9.tar.gz https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
            tar -xzvf chruby-0.3.9.tar.gz
            cd chruby-0.3.9/
            sudo make install
      - run: ruby-install ruby 2.7.7
      - run:
          name: Set chruby
          command: |
            echo 'source /usr/local/share/chruby/chruby.sh' >> $BASH_ENV
            echo 'chruby ruby-2.7.7' >> $BASH_ENV 
      - run: ruby -v
      - run: rvm install bundler
      - run: bundle install
      - run:
          name: fastlane deploy playstore 
          command: bundle exec fastlane playstore


workflows:
  node-android:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node
