version: 2.1
jobs:
  node:
    docker:
      - image: cimg/node:19.2.0

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/app_pisces
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
  
  machine:
    ruby:
      version: 2.7.7
    pre:
      - git clone https://github.com/rbenv/ruby-build.git && cd ruby-build && sudo sh install.sh
      - rbenv install 2.7.7
      - rbenv global 2.7.7
      - cd $CIRCLE_PROJECT_REPONAME && sudo gem update --system
      - sudo gem install bundler
      - bundle install
            
  android-build-and-test:
    working_directory: ~/app_pisces
    docker:
      - image: cimg/android:2022.09
    steps:
      - checkout:
          path: ~/app_pisces
      - attach_workspace:
          at: ~/app_pisces
      - machine
      - run:
          name: fastlane deploy playstore 
          command: bundle exec fastlane playstore


workflows:
  node-android:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node
