version: 2.1

orbs:
  android: circleci/android@2.1.2
  node: circleci/node@5.0.2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@8"
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test
  test-fastlane:
    docker:
      - image: cimg/android:2022.07
    resource_class: large
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: "16.13.0"
      - run: npm install
      - android/decode-keystore:
          keystore-location: android/app/keystore
      - android/create-keystore-properties:
          working-directory: android
      - android/create-google-play-key:
          working-directory: android
      - android/fastlane-deploy:
          working-directory: android
          lane-name: internal

workflows:
  build:
    jobs:
      - build
  deploy:
    jobs:
      - android/deploy-to-play-store:
          executor:
            name: android/android-docker
            tag: "2022.0.7"
          base64-keystore: BASE64_KEYSTORE
          release-key-alias: RELEASE_KEY_ALIAS
          release-key-password: RELEASE_KEY_PASSWORD
          release-keystore: ./keystore
          release-store-password: RELEASE_STORE_PASSWORD
          keystore-properties-working-directory: '.'
          google-play-key: GOOGLE_PLAY_KEY
          lane-name: deploy
          fastlane-working-directory: '.'