version: 2.1
jobs:
  node:
    docker:
      - image: cimg/node:19.2.0

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/app_pisces
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  android-build-and-test:
    working_directory: ~/app_pisces
    docker:
      - image: reactnativecommunity/react-native-android
    steps:
      - checkout:
          path: ~/app_pisces

      - attach_workspace:
          at: ~/app_pisces

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: create keystore file 
          command: |
            cd ./android/app
            echo $BASE64_KEYSTORE | base64 -d > apk.keystore

      - run:
          name: fastlane deploy playstore 
          command: |
            bundle install
            bundle exec fastlane deploy
          working_directory: android

workflows:
  node-android:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node
